### ISSUE TITLE
FuzzyLikeThisQueryBuilder misprint

### ISSUE THREAD

**Issue by komelgman** [wikimedia/search-extra#1]
Hi, I think in [229](https://github.com/wikimedia/search-extra/blob/master/src/main/java/org/wikimedia/search/extra/fuzzylike/FuzzyLikeThisQueryBuilder.java#L229) code line have a misprint. 

`} else if (parseContext.getParseFieldMatcher().match(currentFieldName, ANALYZER)) {
    analyzer = parser.text();
} else if (parseContext.getParseFieldMatcher().match(currentFieldName, ANALYZER)) {
    failOnUnsupportedField = parser.booleanValue();
} else {`

Best regards,
Sergey

**Comment by nomoa** [comment]
Good catch, thanks!

I'll send a quick fix tomorrow.
